// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGI5oaMlXf85VkLzEDgYLnj21SgYUyOeU',
    appId: '1:528508584293:web:bd0d0ef06679d4a9a3618c',
    messagingSenderId: '528508584293',
    projectId: 'flutter-firebase-dersler-b6115',
    authDomain: 'flutter-firebase-dersler-b6115.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-b6115.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAagfFR1YiQFPXWAvd60x8tauUueO1vGdo',
    appId: '1:528508584293:android:306db220be8aac4da3618c',
    messagingSenderId: '528508584293',
    projectId: 'flutter-firebase-dersler-b6115',
    storageBucket: 'flutter-firebase-dersler-b6115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVuXXo62gwAOUZ_ZQgmVhVuxRzbvIwSiU',
    appId: '1:528508584293:ios:38b139af8c80f91da3618c',
    messagingSenderId: '528508584293',
    projectId: 'flutter-firebase-dersler-b6115',
    storageBucket: 'flutter-firebase-dersler-b6115.appspot.com',
    iosBundleId: 'com.example.bolum30FirebaseAuthenticationIslemleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVuXXo62gwAOUZ_ZQgmVhVuxRzbvIwSiU',
    appId: '1:528508584293:ios:93102fcaf538a89ca3618c',
    messagingSenderId: '528508584293',
    projectId: 'flutter-firebase-dersler-b6115',
    storageBucket: 'flutter-firebase-dersler-b6115.appspot.com',
    iosBundleId: 'com.example.bolum30FirebaseAuthenticationIslemleri.RunnerTests',
  );
}
